### PR TITLE
Use smaller and compressed varients of buttons and form components

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by wanglam** [comment]
@AMoo-Miki Thanks, is this PR target for 2.17.0? Can we link the related issue?

**Comment by AMoo-Miki** [comment]
@wanglam this is part of the Look & Feel, to increase density.

**Review by wanglam — APPROVED** [review]
LGTM!

**Review by raintygao — APPROVED** [review]

**Comment by AMoo-Miki** [comment]
I would be grateful if you merged this.

**Pull request merged**
